// Production-subpath check for the voice-capture VAD assets (#339). The
// root-mounted smoke suite cannot see it: octos serves the web client at
// `/app/`, and root-relative `/vad/` asset URLs 404 against that mount. This
// spec spawns its own Vite dev server with `--base /app/` (the same shape as
// the production mount) and drives the real capture hook through
// tests/fixtures/voice-capture-probe.ts, asserting every VAD asset request
// lands under /app/vad/ and actually serves.
import { type ChildProcess, spawn } from "node:child_process";
import { expect, test } from "@playwright/test";

const PORT = 5197;
// Vite 7 binds `localhost` (IPv6 ::1 on macOS/Linux CI images included), so
// address it by name rather than 127.0.0.1.
const ORIGIN = `http://localhost:${PORT}`;
const VAD_PREFIX = `${ORIGIN}/app/vad/`;

const REQUIRED_VAD_ASSETS = [
  "vad.worklet.bundle.min.js",
  "silero_vad_v5.onnx",
  "ort-wasm-simd-threaded.mjs",
  "ort-wasm-simd-threaded.wasm",
] as const;

test.use({
  launchOptions: {
    args: [
      "--use-fake-device-for-media-stream",
      "--use-fake-ui-for-media-stream",
    ],
  },
});

let vite: ChildProcess | null = null;

// Mirrors tests/fixtures/voice-capture-probe.ts.
interface VadProbeState {
  started: boolean;
  done: boolean;
  capturing: boolean;
  error: string | null;
}

function readProbe(page: import("@playwright/test").Page) {
  return page.evaluate(
    () => (window as unknown as { __vadProbe: VadProbeState }).__vadProbe,
  );
}

test.beforeAll(async () => {
  // public/vad/ is gitignored (generated by predev/prebuild); the CI checkout
  // does not have it, so materialize it before serving.
  await new Promise<void>((resolve, reject) => {
    const copy = spawn("node", ["scripts/copy-vad-assets.mjs"], {
      stdio: "inherit",
    });
    copy.on("exit", (code) =>
      code === 0
        ? resolve()
        : reject(new Error(`copy-vad-assets exited with ${code}`)),
    );
  });

  vite = spawn(
    "./node_modules/.bin/vite",
    ["--port", String(PORT), "--strictPort", "--base", "/app/"],
    { stdio: "pipe" },
  );
  const deadline = Date.now() + 60_000;
  while (Date.now() < deadline) {
    try {
      const response = await fetch(`${ORIGIN}/app/`);
      if (response.ok) return;
    } catch {
      // server not up yet
    }
    await new Promise((resolve) => setTimeout(resolve, 500));
  }
  throw new Error("subpath vite dev server did not become ready");
});

test.afterAll(async () => {
  if (!vite) return;
  const proc = vite;
  proc.kill("SIGTERM");
  await new Promise<void>((resolve) => {
    proc.on("exit", () => resolve());
    setTimeout(() => {
      proc.kill("SIGKILL");
      resolve();
    }, 5_000);
  });
});

test("voice capture resolves its VAD assets under the /app base", async ({
  page,
}) => {
  test.setTimeout(120_000);
  await page.context().grantPermissions(["microphone"]);

  const vadResponses: Array<{ url: string; status: number }> = [];
  const vadFailures: Array<{ url: string; error: string }> = [];
  page.on("response", (response) => {
    if (response.url().includes("/vad/")) {
      vadResponses.push({ url: response.url(), status: response.status() });
    }
  });
  page.on("requestfailed", (request) => {
    if (request.url().includes("/vad/")) {
      vadFailures.push({
        url: request.url(),
        error: request.failure()?.errorText ?? "unknown",
      });
    }
  });

  // The probe does not need a backend; keep the SPA shell's /api calls from
  // hitting the absent dev proxy while it boots.
  await page.route("**/api/**", (route) =>
    route.fulfill({ status: 503, body: "backend absent in probe" }),
  );

  await page.goto(`${ORIGIN}/app/`);
  await page.evaluate(() => import("/app/tests/fixtures/voice-capture-probe.ts"));

  // Cold ONNX model load in CI can take a while.
  await page.waitForFunction(
    () => {
      const probe = (window as unknown as {
        __vadProbe?: { done: boolean; capturing: boolean; error: string | null };
      }).__vadProbe;
      return Boolean(probe?.done) && (probe?.capturing || probe?.error);
    },
    undefined,
    { timeout: 90_000 },
  );

  const probe = await readProbe(page);
  expect(probe.error, "capture start should not fail").toBeNull();
  expect(probe.capturing, "capture should be live").toBe(true);

  // No VAD asset request may escape the app base — pre-fix they went to the
  // root and 404'd against the /app/ mount.
  //
  // Chromium reports every bodyless HEAD as requestfailed ERR_ABORTED right
  // after delivering its 200, so a failure is only fatal when the URL never
  // got a successful response (the hook's HEAD→GET fallback covers those).
  const okUrls = new Set(
    vadResponses.filter((r) => r.status === 200).map((r) => r.url),
  );
  expect(vadFailures.filter((f) => !okUrls.has(f.url))).toEqual([]);
  expect(vadResponses.length).toBeGreaterThan(0);
  for (const response of vadResponses) {
    expect(
      response.url.startsWith(VAD_PREFIX),
      `${response.url} must live under ${VAD_PREFIX}`,
    ).toBe(true);
    expect(response.status, `${response.url} must serve`).toBe(200);
  }
  for (const asset of REQUIRED_VAD_ASSETS) {
    expect(
      vadResponses.some(
        (response) =>
          response.url === `${VAD_PREFIX}${asset}` && response.status === 200,
      ),
      `${asset} must be requested and served under /app/vad/`,
    ).toBe(true);
  }
});
