import type { LessonPacketV1 } from "./lesson-packet";

export const QUADRATIC_DEMO_PACKET: LessonPacketV1 = {
  version: 1,
  lessonId: "quadratic-vertex-demo",
  turnId: "demo-turn-1",
  title: "二次函数的顶点与图像",
  segments: [
    {
      id: "intro",
      speech: "我们先不背顶点公式，试着把它变成一个完全平方。",
      actions: [
        {
          id: "focus-solution",
          type: "focus",
          at: { x: 620, y: 360 },
          zoom: 0.9,
        },
        {
          id: "topic",
          type: "write_text",
          text: "二次函数的顶点与图像",
          at: { x: 320, y: 110 },
          size: "xl",
          tone: "accent",
          semanticLevel: "topic",
        },
        {
          id: "question-label",
          type: "write_text",
          text: "问题",
          at: { x: 80, y: 230 },
          size: "sm",
          tone: "muted",
          semanticLevel: "summary",
        },
        {
          id: "question",
          type: "write_formula",
          latex: "y=x^2-4x+3",
          at: { x: 80, y: 275 },
          size: "lg",
          semanticLevel: "summary",
        },
        {
          id: "question-note",
          type: "write_text",
          text: "为什么顶点是 (2, -1)？图像怎么画？",
          at: { x: 80, y: 335 },
          size: "sm",
          semanticLevel: "detail",
        },
      ],
    },
    {
      id: "complete-square",
      speech: "在中间补上四，再减去四，原式的值没有发生变化。",
      actions: [
        {
          id: "step-label",
          type: "write_text",
          text: "配方法",
          at: { x: 470, y: 230 },
          size: "sm",
          tone: "muted",
          semanticLevel: "summary",
        },
        {
          id: "formula-original",
          type: "write_formula",
          latex: "y=x^2-4x+3",
          at: { x: 470, y: 275 },
          size: "lg",
          semanticLevel: "detail",
        },
        {
          id: "formula-expanded",
          type: "write_formula",
          latex: "=\\left(x^2-4x+4\\right)-4+3",
          at: { x: 470, y: 345 },
          size: "lg",
          semanticLevel: "detail",
        },
        {
          id: "balance-highlight",
          type: "highlight",
          targetId: "formula-expanded",
          label: "+4 与 -4 抵消",
          color: "blue",
        },
      ],
    },
    {
      id: "vertex-form",
      speech: "这样就得到顶点式，平方项最小只能等于零。",
      actions: [
        {
          id: "formula-vertex",
          type: "write_formula",
          latex: "=\\left(x-2\\right)^2-1",
          at: { x: 470, y: 430 },
          size: "xl",
          tone: "accent",
          semanticLevel: "summary",
        },
        {
          id: "minimum",
          type: "write_formula",
          latex: "\\left(x-2\\right)^2\\ge 0",
          at: { x: 520, y: 520 },
          size: "md",
          semanticLevel: "detail",
        },
        {
          id: "vertex",
          type: "write_text",
          text: "当 x = 2 时，y 最小 = -1　→　顶点 (2, -1)",
          at: { x: 470, y: 585 },
          size: "md",
          tone: "accent",
          semanticLevel: "summary",
        },
        {
          id: "vertex-highlight",
          type: "highlight",
          targetId: "vertex",
          color: "yellow",
        },
      ],
    },
    {
      id: "graph",
      speech: "现在把顶点和对称轴放进坐标系，图像就很清楚了。",
      actions: [
        {
          id: "focus-graph",
          type: "focus",
          at: { x: 1110, y: 390 },
          zoom: 0.9,
        },
        {
          id: "graph-label",
          type: "write_text",
          text: "用图像验证",
          at: { x: 900, y: 190 },
          size: "sm",
          tone: "muted",
          semanticLevel: "summary",
        },
        {
          id: "axes",
          type: "draw_axes",
          at: { x: 900, y: 235 },
          width: 500,
          height: 400,
          xDomain: [-1, 5],
          yDomain: [-2, 7],
        },
        {
          id: "parabola",
          type: "plot_function",
          function: {
            kind: "quadratic",
            coefficients: [1, -4, 3],
          },
          axesId: "axes",
          color: "blue",
        },
        {
          id: "vertex-point",
          type: "mark_point",
          axesId: "axes",
          point: [2, -1],
          label: "顶点 (2, -1)",
          color: "coral",
        },
      ],
    },
    {
      id: "organize",
      speech: "配方法告诉我们顶点，顶点和对称轴又决定了图像。",
      actions: [
        {
          id: "group-method",
          type: "group",
          title: "配方法",
          summary: "一般式 → 顶点式",
          at: { x: 430, y: 190 },
          width: 390,
          height: 475,
          memberIds: [
            "formula-original",
            "formula-expanded",
            "formula-vertex",
            "minimum",
            "vertex",
          ],
        },
        {
          id: "group-graph",
          type: "group",
          title: "函数图像",
          summary: "顶点 · 对称轴 · 开口方向",
          at: { x: 860, y: 160 },
          width: 580,
          height: 520,
          memberIds: ["axes", "parabola", "vertex-point"],
        },
        {
          id: "method-to-graph",
          type: "connect",
          fromId: "group-method",
          toId: "group-graph",
          label: "决定",
        },
      ],
    },
    {
      id: "checkpoint",
      speech: "最后试一题。函数 y 等于 x 平方加六 x 加五，它的对称轴是多少？",
      actions: [
        {
          id: "checkpoint-card",
          type: "checkpoint",
          prompt: "试一试：y = x² + 6x + 5 的对称轴是多少？",
          at: { x: 520, y: 760 },
        },
        {
          id: "focus-checkpoint",
          type: "focus",
          at: { x: 820, y: 730 },
          zoom: 0.85,
        },
      ],
    },
  ],
};
