import { useEffect, useRef, useState } from "react";
import { useSession } from "@/runtime/session-context";
import { eventMatchesScope } from "@/runtime/event-scope";

// Default fall-back word. The server-side `StatusIndicator` rotates
// through a creative pool (`Pondering`, `Brewing`, `Synthesizing`, etc.)
// generated by `PersonaService` and dispatches `crew:status_word` events
// when the server-side wiring lands. Until then we still render a
// pleasant bubble with this fallback word.
const DEFAULT_WORD = "Thinking";

function formatTokens(n: number): string {
  if (n >= 1000) return `${(n / 1000).toFixed(1)}k`;
  return String(n);
}

function formatElapsed(secs: number): string {
  // Match the gateway's `format_status` ergonomics — suppress the
  // time strip for the first couple of seconds so it doesn't flicker
  // a "0s" badge as soon as the bubble appears.
  if (secs < 3) return "";
  if (secs < 60) return `${secs}s`;
  const m = Math.floor(secs / 60);
  const s = secs % 60;
  return `${m}m ${s}s`;
}

export function ThinkingIndicator() {
  const { currentSessionId, historyTopic } = useSession();
  const [active, setActive] = useState<{ iteration: number } | null>(null);
  const [word, setWord] = useState<string>(DEFAULT_WORD);
  const [tokens, setTokens] = useState<{ input: number; output: number }>({
    input: 0,
    output: 0,
  });
  const [elapsed, setElapsed] = useState(0);
  const startedAtRef = useRef<number | null>(null);

  useEffect(() => {
    function thinkingHandler(e: Event) {
      const detail = (e as CustomEvent).detail;
      if (!eventMatchesScope(detail, currentSessionId, historyTopic)) return;
      if (detail.thinking) {
        if (startedAtRef.current == null) {
          startedAtRef.current = Date.now();
        }
        setActive({ iteration: detail.iteration ?? 0 });
      } else {
        startedAtRef.current = null;
        setActive(null);
        setElapsed(0);
        setTokens({ input: 0, output: 0 });
        setWord(DEFAULT_WORD);
      }
    }

    function costHandler(e: Event) {
      const detail = (e as CustomEvent).detail;
      if (!eventMatchesScope(detail, currentSessionId, historyTopic)) return;
      // `crew:cost` wire field names match the server-side snake_case
      // (`input_tokens` / `output_tokens`) — see
      // `ui-protocol-event-router.ts` `crew:cost` dispatcher. These
      // are session-cumulative counters; the gateway's StatusIndicator
      // shows them as-is, so we follow the same convention here.
      const input = typeof detail.input_tokens === "number" ? detail.input_tokens : 0;
      const output = typeof detail.output_tokens === "number" ? detail.output_tokens : 0;
      setTokens({ input, output });
    }

    function statusWordHandler(e: Event) {
      const detail = (e as CustomEvent).detail;
      if (!eventMatchesScope(detail, currentSessionId, historyTopic)) return;
      // Server emits a creative status word every ~8s from the
      // `StatusIndicator` pool. Words are language-matched (Chinese
      // vs English) based on the inbound user message. Until the
      // server-side `progress/status_word` event lands this listener
      // is dormant and the bubble shows DEFAULT_WORD.
      if (typeof detail.word === "string" && detail.word.length > 0) {
        setWord(detail.word);
      }
    }

    window.addEventListener("crew:thinking", thinkingHandler);
    window.addEventListener("crew:cost", costHandler);
    window.addEventListener("crew:status_word", statusWordHandler);
    return () => {
      window.removeEventListener("crew:thinking", thinkingHandler);
      window.removeEventListener("crew:cost", costHandler);
      window.removeEventListener("crew:status_word", statusWordHandler);
    };
  }, [currentSessionId, historyTopic]);

  useEffect(() => {
    if (!active) return;
    const tick = () => {
      if (startedAtRef.current != null) {
        setElapsed(Math.floor((Date.now() - startedAtRef.current) / 1000));
      }
    };
    tick();
    const id = window.setInterval(tick, 1000);
    return () => window.clearInterval(id);
  }, [active]);

  if (!active) return null;

  const timeStr = formatElapsed(elapsed);
  const hasTokens = tokens.input > 0 || tokens.output > 0;
  const tokenStr = hasTokens
    ? `${formatTokens(tokens.input)}↑ ${formatTokens(tokens.output)}↓`
    : "";
  const detailParts = [timeStr, tokenStr].filter(Boolean);
  const detail = detailParts.join(" · ");

  return (
    <div
      data-testid="thinking-indicator"
      className="inline-flex items-center gap-2 my-1 px-3 py-2 rounded-lg border border-accent/30 bg-accent-container text-sm shadow-sm"
      role="status"
      aria-live="polite"
    >
      <span
        className="text-accent text-base leading-none animate-pulse select-none"
        aria-hidden="true"
      >
        ✦
      </span>
      <span className="text-text">
        <span className="font-medium text-text-strong">{word}</span>
        <span className="text-muted">…</span>
        {detail && <span className="text-muted ml-1.5">({detail})</span>}
      </span>
    </div>
  );
}
